__index__:
  - hdmi_optics
  - pixera_output
  - dante_audio
  - companion_buttons
  - nodered_flows
  - millumin_signal
  - artnet_timecode

hdmi_optics:
  match: ["hdmi","оптик","kramer","teranex","плазм","no signal"]
  title: "HDMI/Оптика: быстрый чек-лист"
  now:
    - "Проверь направленность оптического HDMI (Source → Display)."
    - "Принудительно выставь 1080p60 на источнике и проверь картинку."
    - "Проверь питание/индикацию конвертеров, перезапусти."
    - "Обойди другой вход дисплея и/или другой кабель."
  if_fail:
    - "Оставь 1080p60 до конца мероприятия."
    - "Поменяй конвертер или проложи короткий медный HDMI для теста."
  notes:
    - "Часто причина — EDID или перевёрнутый тракт."

pixera_output:
  match: ["pixera","пиксер","сервер","output","таймлайн"]
  title: "Pixera: нет вывода/не видит дисплей"
  now:
    - "Проверь, включён ли нужный output в настройках."
    - "Снизь режим до 1080p60 для теста."
    - "Перезапусти проект Pixera или приложение."
    - "Проверь внешний тракт по чек-листу HDMI/Оптика."
  if_fail: ["Включи резервный выход/плеер."]
  notes: ["Часто — несоответствие режима (EDID) или кабель/конвертер."]

dante_audio:
  match: ["dante","звук","audio"]
  title: "Dante: нет звука"
  now:
    - "Открой Dante Controller и проверь подписки (Routing)."
    - "Проверь clock master и sample rate."
    - "Проверь линк на свитче/интерфейсах."
  if_fail: ["Дай аварийный локальный выход в устройство."]
  notes: ["Часто — сброс подписок или конфликт частоты."]

companion_buttons:
  match: ["companion","stream deck","кнопк"]
  title: "Companion: кнопки не срабатывают"
  now:
    - "Проверь, что Companion запущен и активен нужный профиль."
    - "Проверь связь с устройством (IP/порт, API online)."
    - "Перезапусти модуль/приложение."
  if_fail: ["Делай действия вручную в целевом софте."]
  notes: ["Часто — сменился IP или устройство не в сети."]

nodered_flows:
  match: ["node-red","flows","автоматизац"]
  title: "Node-RED: flow не отрабатывает"
  now:
    - "Открой веб-панель Node-RED и проверь status у узлов."
    - "Перезапусти сервис Node-RED."
    - "Проверь доступность внешних API/устройств."
  if_fail: ["Сделай действие вручную, минуя автоматизацию."]
  notes: ["Часто — залипание узла или потеря соединения."]

millumin_signal:
  match: ["millumin","миллюмин"]
  title: "Millumin: пропал сигнал/чёрный экран"
  now:
    - "Переключи слой/композицию."
    - "Проверь устройства захвата/выходы."
    - "Перезапусти Millumin с проектом."
  if_fail: ["Переведи показ на резервный источник."]
  notes: ["Иногда ломается при показе PDF вместо PPTX."]

artnet_timecode:
  match: ["artnet","timecode","таймкод"]
  title: "ArtNet/Timecode: нет синхры"
  now:
    - "Проверь сетевое подключение (UDP/VLAN/свитч)."
    - "Сверь FPS таймкода с проектом (25 vs 30)."
    - "Перезапусти генератор таймкода и приём на Pixera/консолях."
  if_fail: ["Временно запускай вручную по таймметкам."]
  notes: ["Часто — фильтрация пакетов или неверный FPS."]
